package helpers

const (
	FAILED_TO_CREATE_ELEMENT = "FAILED_TO_CREATE_ELEMENT"
	FAILED_TO_UPDATE_ELEMENT = "FAILED_TO_UPDATE_ELEMENT"
	FAILED_TO_DELETE_ELEMENT = "FAILED_TO_DELETE_ELEMENT"
	FAILED_TO_GET_ELEMENTS   = "FAILED_TO_GET_ELEMENTS"
	SONG_ALREADY_EXIST       = "SONG_ALREADY_EXIST"
	FAILED_TO_ROLLBACK       = "FAILED TO ROLLBACK"
	FAILED_TO_CLOSE          = "FAILED TO CLOSE"
	REQUEST_ERROR            = "REQUEST_ERROR"

	JSON_PARSE_ERROR = "JSON_PARSE_ERROR"
	SUCCESS          = "SUCCESS"

	DEFAULT_VALUE_FOR_FIELDS = "NOT FOUND"

	APP_PREFIX = " [ APP ] "

	INFO_PREFIX     = " INFO "
	STATUS_PREFIX   = " STATUS "
	RESPONSE_PREFIX = " [ RESPONSE ] "
	UNMARSHAL_ERROR = "UNMARSHAL_ERROR"
	READ_BODY_ERROR = "READ_BODY_ERROR"

	RECONECT_DB           = "RECONNECTING TO DATABASE..."
	DISCONNECT_DB         = "DISCONNECTED FROM DATABASE"
	PG_PREFIX             = " [ POSTGRES ] "
	PG_CONNECTION_FAILED  = "FAILED TO CONNECT TO DATABASE"
	PG_CONNECT_SUCCESS    = "SUCCESSFULLY CONNECTED TO POSTGRES"
	PG_TRANSACTION_FAILED = "FAILED TO FETCH TRANSACTION"
	PG_COMMIT_FAILED      = "FAILED TO COMMIT TRANSACTION"

	PG_MIGRATION_FAILED = "FAILED TO MIGRATE DATABASE"
	NO_ROWS_AFFECTED    = "NO ROWS AFFECTED"
)
