package helpers

const (
	CANNOT_FIND_ELEMENT_BY_ID = "CANNOT_FIND_ELEMENT_BY_ID"
	CANNOT_FIND_ELEMENS       = "CANNOT_FIND_ELEMENTS"

	FAILED_TO_CREATE_ELEMENT = "FAILED_TO_CREATE_ELEMENT"
	FAILED_TO_UPDATE_ELEMENT = "FAILED_TO_UPDATE_ELEMENT"
	FAILED_TO_DELETE_ELEMENT = "FAILED_TO_DELETE_ELEMENT"
	FAILED_TO_GET_ELEMENTS   = "FAILED_TO_GET_ELEMENTS"
	SONGS_NOT_FOUND          = "SONGS_NOT_FOUND"
	PG_DELETE_FAILED         = "FAILED TO DELETE DATA"
	FAILED_TO_ROLLBACK       = "FAILED TO ROLLBACK"
	FAILED_TO_CLOSE          = "FAILED TO CLOSE"

	USER_NOT_FOUND = "USER_NOT_FOUND"
	UNAUTHORIZED   = "UNAUTHORIZED"

	JSON_PARSE_ERROR = "JSON_PARSE_ERROR"
	SUCCESS          = "SUCCESS"

	MOCK_URL = "https://fc4030401c5421b0.mokky.dev"
)
